import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { TopNav } from "~/components/TopNav";
import { BottomNav } from "~/components/BottomNav";
import { Promotion } from "~/components/Promotion";
import { Event } from "~/components/Event";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  const eventList = [{
    name: "test", pic: "test", time: "test"
  }, {
    name: "test", pic: "test", time: "test"
  }, {
    name: "test", pic: "test", time: "test"
  },{
    name: "test", pic: "test", time: "test"
  }]

  return (
    <div className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="sticky top-0 z-50 backdrop-blur-lg" >
        <TopNav />
      </div>
      <div className="p-5 bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
          <Promotion />
      </div>
      {/* Main List */}
      <main className="flex min-h-screen pb-20 flex-col items-center justify-center bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500">
        {/* Promotion */}
        

        {eventList.map((_evt, index) => {
            return <Event key={index} />
          }
        )}

        {/* Bottom Navigation */}
        <BottomNav />
      </main>
    </div>
  );
};

export default Home;
